// <auto-generated />
using System;
using DocumentService.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DocumentService.Migrations
{
    [DbContext(typeof(DokumentContext))]
    [Migration("20220222225537_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DocumentService.Entities.Dokument", b =>
                {
                    b.Property<Guid>("DokumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumDonosenjaOdluke")
                        .HasColumnType("datetime2");

                    b.Property<string>("NazivDokumenta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sablon")
                        .HasColumnType("bit");

                    b.Property<Guid>("TipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZavodniBroj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DokumentID");

                    b.ToTable("Dokument");

                    b.HasData(
                        new
                        {
                            DokumentID = new Guid("6a411c13-a195-48f7-8dbd-67596c3975a3"),
                            Datum = new DateTime(2020, 12, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumDonosenjaOdluke = new DateTime(2021, 10, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            NazivDokumenta = "Dokument1",
                            Sablon = true,
                            TipId = new Guid("10d3f482-9538-448f-9399-bbbade1bc504"),
                            ZavodniBroj = "1"
                        },
                        new
                        {
                            DokumentID = new Guid("6a411c13-a195-48f7-8dbd-67596c3972b2"),
                            Datum = new DateTime(2019, 6, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumDonosenjaOdluke = new DateTime(2021, 5, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            NazivDokumenta = "Dokument2",
                            Sablon = false,
                            TipId = new Guid("9ddfc708-5a68-40ba-b76c-95b27e63ba9a"),
                            ZavodniBroj = "2"
                        });
                });

            modelBuilder.Entity("DocumentService.Entities.TipDokumentaEntity.TipDokumentaE", b =>
                {
                    b.Property<Guid>("TipDokumentaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusDokumenta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipDokumenta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipDokumentaID");

                    b.ToTable("tipDokumenta");

                    b.HasData(
                        new
                        {
                            TipDokumentaID = new Guid("6a411c13-a195-48f7-8dbd-67596c3975b2"),
                            StatusDokumenta = "Usvojen",
                            TipDokumenta = "Sablon"
                        },
                        new
                        {
                            TipDokumentaID = new Guid("6a411c13-a195-48f7-8dbd-67596c3975b1"),
                            StatusDokumenta = "Odbijen",
                            TipDokumenta = "Negenericki"
                        },
                        new
                        {
                            TipDokumentaID = new Guid("6a411c13-a195-48f7-8dbd-67596c3974a2"),
                            StatusDokumenta = "Otvoren",
                            TipDokumenta = "Sablon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
