// <auto-generated />
using System;
using Lice.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lice.Migrations
{
    [DbContext(typeof(LiceContext))]
    partial class LiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lice.Entities.LiceEntity", b =>
                {
                    b.Property<Guid>("liceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("brojRacuna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("brojTelefona1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("brojTelefona2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("liceId");

                    b.ToTable("Lica");

                    b.HasDiscriminator<string>("Discriminator").HasValue("LiceEntity");
                });

            modelBuilder.Entity("Lice.Entities.FizickoLiceEntity", b =>
                {
                    b.HasBaseType("Lice.Entities.LiceEntity");

                    b.Property<string>("ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("FizickoLiceEntity");

                    b.HasData(
                        new
                        {
                            liceId = new Guid("71b99b68-8e8f-4cc3-b8d2-d6badc704221"),
                            brojRacuna = "brRac1",
                            brojTelefona1 = "123456",
                            brojTelefona2 = "789456",
                            email = "email1",
                            ime = "Ime1",
                            prezime = "Prezime1"
                        });
                });

            modelBuilder.Entity("Lice.Entities.PravnoLiceEntity", b =>
                {
                    b.HasBaseType("Lice.Entities.LiceEntity");

                    b.Property<int>("faks")
                        .HasColumnType("int");

                    b.Property<string>("naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("PravnoLiceEntity");

                    b.HasData(
                        new
                        {
                            liceId = new Guid("25499084-4d50-412b-9640-1ab07af33d4d"),
                            brojRacuna = "brRac2",
                            brojTelefona1 = "456123",
                            brojTelefona2 = "45214",
                            email = "email2",
                            faks = 125,
                            naziv = "PravnoLice1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
