// <auto-generated />
using System;
using Adresa.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Adresa.Migrations
{
    [DbContext(typeof(AdresaContext))]
    partial class AdresaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Adresa.Entities.AdresaEntity", b =>
                {
                    b.Property<Guid>("AdresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Broj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DrzavaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mesto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostanskiBroj")
                        .HasColumnType("int");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdresaId");

                    b.HasIndex("DrzavaId");

                    b.ToTable("Adrese");

                    b.HasData(
                        new
                        {
                            AdresaId = new Guid("6a411c13-a195-48f7-8dbd-67596c3974c0"),
                            Broj = "1",
                            DrzavaId = new Guid("170960f3-f8e0-4614-aff2-653aadf5c720"),
                            Mesto = "Subotica",
                            PostanskiBroj = 24000,
                            Ulica = "Ane Frank"
                        },
                        new
                        {
                            AdresaId = new Guid("32cd906d-8bab-457c-ade2-fbc4ba523029"),
                            Broj = "23",
                            DrzavaId = new Guid("170960f3-f8e0-4614-aff2-653aadf5c720"),
                            Mesto = "Subotica",
                            PostanskiBroj = 24000,
                            Ulica = "Apatinska"
                        });
                });

            modelBuilder.Entity("Adresa.Entities.DrzavaEntity", b =>
                {
                    b.Property<Guid>("DrzavaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivDrzave")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DrzavaId");

                    b.ToTable("Drzave");

                    b.HasData(
                        new
                        {
                            DrzavaId = new Guid("170960f3-f8e0-4614-aff2-653aadf5c720"),
                            NazivDrzave = "Srbija"
                        },
                        new
                        {
                            DrzavaId = new Guid("c8a9ffbc-db56-46ff-a54a-948c91550189"),
                            NazivDrzave = "Mađarska"
                        });
                });

            modelBuilder.Entity("Adresa.Entities.AdresaEntity", b =>
                {
                    b.HasOne("Adresa.Entities.DrzavaEntity", "Drzava")
                        .WithMany()
                        .HasForeignKey("DrzavaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drzava");
                });
#pragma warning restore 612, 618
        }
    }
}
