// <auto-generated />
using System;
using Licitacija.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Licitacija.Migrations
{
    [DbContext(typeof(LicitacijaContext))]
    [Migration("20220220094622_LicitacijaFirst")]
    partial class LicitacijaFirst
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Licitacija.Entities.LicitacijaModel", b =>
                {
                    b.Property<Guid>("licitacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("brojLicitacije")
                        .HasColumnType("int");

                    b.Property<DateTime>("datumRaspisivanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("dokumentId")
                        .HasColumnType("int");

                    b.Property<int>("godinaLicitacije")
                        .HasColumnType("int");

                    b.Property<int>("javnoNadmetanjeId")
                        .HasColumnType("int");

                    b.Property<int>("krugLicitacije")
                        .HasColumnType("int");

                    b.Property<int>("ogranicenje")
                        .HasColumnType("int");

                    b.Property<DateTime>("rokZaPrijave")
                        .HasColumnType("datetime2");

                    b.HasKey("licitacijaId");

                    b.ToTable("Licitacija");

                    b.HasData(
                        new
                        {
                            licitacijaId = new Guid("6a411c13-a195-48f7-8dbd-67596c3974c0"),
                            brojLicitacije = 1,
                            datumRaspisivanja = new DateTime(2021, 6, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            dokumentId = 1,
                            godinaLicitacije = 2021,
                            javnoNadmetanjeId = 1,
                            krugLicitacije = 1,
                            ogranicenje = 0,
                            rokZaPrijave = new DateTime(2021, 7, 1, 23, 59, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            licitacijaId = new Guid("1c7ea607-8ddb-493a-87fa-4bf5893e965b"),
                            brojLicitacije = 2,
                            datumRaspisivanja = new DateTime(2021, 11, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            dokumentId = 2,
                            godinaLicitacije = 2022,
                            javnoNadmetanjeId = 2,
                            krugLicitacije = 1,
                            ogranicenje = 1,
                            rokZaPrijave = new DateTime(2021, 11, 25, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
